### ISSUE TITLE
Snap to each segment

### ISSUE THREAD

**Issue by fire** [tavurth/godot-radial-menu#3]
Hi I was looking at your code,

Do you know how to make it is snap to each section and provide a line from the center to the cursor?

**Comment by tavurth** [comment]
Hey I'm on a motorcycle tour at the moment but I can give some pointers.

The current index of the cursor is determined by the following function:

https://github.com/tavurth/godot-radial-menu/blob/6a67b2b5038afe4187f0dedf76ce24a605faa2df/addons/radial_menu/CursorPos.gd#L16-L33

However this is for code logic, to actually render the cursor position we use shader code, which can be found here:

https://github.com/tavurth/godot-radial-menu/blob/6a67b2b5038afe4187f0dedf76ce24a605faa2df/addons/radial_menu/selector.shader#L50-L63


To snap to Index, you would probably just convert the position of the current degree to snapped percentage based on the number of items you have in your selection. That can be found in this line:

https://github.com/tavurth/godot-radial-menu/blob/6a67b2b5038afe4187f0dedf76ce24a605faa2df/addons/radial_menu/selector.shader#L56

About a line from the center, perhaps you can draw a small diagram to help me understand what you're going for?

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/173916409-21a797d4-f36b-4dec-b2f7-f032081a1dcd.png)

**Comment by tavurth** [comment]
If the line should reach the cursor wherever it is on screen, then I would use a canvas layer and just draw that line in a shader.

The Shader in my code only applies to the circle, so it would be easier to use an overlay. Or you could just use a `Line2D` node on the overlay layer and set the end point to the mouse position.
