### ISSUE TITLE
Child Button Selection

### ISSUE THREAD

**Issue by PeacefulChaos94** [tavurth/godot-radial-menu#5]
Kinda difficult to put my issue into words, so I attached a gif. Basically, I want the RadialMenu's child button(s) pressed signal to only be emitted when the mouse is directly over the child button, rather than just based on the angle the mouse is at. I'm not sure if there's a way around that.
![2022-11-15_11h52_49](https://user-images.githubusercontent.com/96140273/202014091-8ca2cc01-7c24-4478-80b0-48e883ab75bb.gif)

**Comment by PeacefulChaos94** [comment]
I was able to find a workaround, which is to simply comment out the signal connects for the RadialMenu.
![image](https://user-images.githubusercontent.com/96140273/202029443-3ff1a4dc-bf39-4947-92cc-c69c0ce7235a.png)

**Comment by tavurth** [comment]
Glad you got it working!
