### ISSUE TITLE
Minimun items supported 6?

### ISSUE THREAD

**Issue by CGI-Fox** [tavurth/godot-radial-menu#6]
Hello, thank you a lot for this addon, I know this is no a continued addon, but can you please help me with this issue?

You can see this issue just deleting 4 buttoms in your ExampleScene; It don´t select/hover on the right buttoms.

Edit: Also when you start the script or unhide the node, it dont module the first item hovering unless you hover in another item.

**Comment by tavurth** [comment]
Hi, it's on my TODO list to take a look at this issue but it may still be a little while

**Comment by tavurth** [comment]
Should be fixed now :)
